substitutions:
  buzzer_pin: GPIO9
  i2s_bclk_pin: GPIO36    # SCK
  i2s_din_pin: GPIO38     # mic
  i2s_dout_pin: GPIO40    # speaker
  i2s_lrclk_pin: GPIO34   # WS
  led_invert: "true"
  led_pin: GPIO15
  pir_pin: GPIO11
  sen0395_io_pin: GPIO5
  uart_rx_pin: GPIO37
  uart_tx_pin: GPIO39

esp32:
  board: lolin_s2_mini
  flash_size: 4MB
  framework:
    type: esp-idf
    version: latest

i2c:
  sda: GPIO33
  scl: GPIO35

sensor:
  - platform: internal_temperature
    name: "CPU Temperature"
