substitutions:
  buzzer_pin: GPIO13
  i2s_bclk_pin: GPIO38 #SCK
  i2s_din_pin: GPIO37 #SD
  i2s_lrclk_pin: GPIO34 #WS
  i2s_speaker_din_pin: GPIO33
  pir_pin: GPIO11
  rgb_led_pin: GPIO47
  rgb_led_type: RGB
  sen0395_io_pin: GPIO4
  uart_rx_pin: GPIO43
  uart_tx_pin: GPIO44

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    # version: 5.3.1 #https://github.com/espressif/esp-idf/releases
    # platform_version: 6.9.0 #https://github.com/platformio/platform-espressif32/releases/

i2c:
  sda: GPIO35
  scl: GPIO36
  frequency: 400kHz

sensor:
  - platform: internal_temperature
    name: "CPU Temperature"

psram:
  mode: quad
  speed: 80MHz
