substitutions:
  buzzer_pin: GPIO13
  i2s_bclk_pin: GPIO38    # SCK
  i2s_din_pin: GPIO37     # mic
  i2s_dout_pin: GPIO33    # speaker
  i2s_lrclk_pin: GPIO34   # WS
  pir_pin: GPIO11
  rgb_led_pin: GPIO47
  rgb_led_type: RGB
  sen0395_io_pin: GPIO4
  uart_rx_pin: GPIO44
  uart_tx_pin: GPIO43

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 4MB
  framework:
    type: esp-idf
    version: latest

i2c:
  sda: GPIO35
  scl: GPIO36
  frequency: 400kHz

sensor:
  - platform: internal_temperature
    name: "CPU Temperature"
