psram:
  mode: quad
  speed: 80MHz

i2s_audio:
  id: i2s_audiobus
  i2s_lrclk_pin: "${i2s_lrclk_pin}"  # WS
  i2s_bclk_pin: "${i2s_bclk_pin}"  # SCK

speaker:
  - platform: i2s_audio
    id: va_speaker
    i2s_dout_pin: ${i2s_dout_pin}
    dac_type: external
    channel: mono

media_player:
  - platform: speaker
    announcement_pipeline:
      speaker: va_speaker
    name: ESPHome I2S Media Player
    id: va_media_player
    on_announcement:
      - light.turn_on:
          id: led
          effect: "Fast Pulse"
    on_idle: 
      - light.turn_off:
          id: led