# https://esphome.io/components/light/neopixelbus.html
substitutions:
  led_strobe_on: 50ms
  led_strobe_off: 100ms

light:
  - platform: esp32_rmt_led_strip
    pin: "${rgb_led_pin}"
    rgb_order: "${rgb_led_type}"
    chipset: ws2812
    name: "LED"
    id: led
    num_leds: 1
    icon: "mdi:led-outline"
    effects:
      - strobe:
          colors:
            - state: true
              duration: "${led_strobe_on}"
            - state: false
              duration: "${led_strobe_off}"
      - strobe:
          name: Alarm
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: "${led_strobe_on}"
            - state: false
              duration: "${led_strobe_off}"
            - state: true
              brightness: 100%
              red: 100%
              green: 100%
              blue: 100%
              duration: "${led_strobe_on}"
            - state: false
              duration: "${led_strobe_off}"
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.1s
          update_interval: 0.4s
      - pulse:
          name: "Slow Pulse"
          transition_length: 1s
          update_interval: 2s

esphome:
  on_boot:
    - priority: 0
      then:
        - light.turn_on: led
        - delay: 2s
        - light.turn_off: led
