i2s_audio:
  id: i2s_in
  i2s_lrclk_pin: "${i2s_lrclk_pin}"  # WS
  i2s_bclk_pin: "${i2s_bclk_pin}"  # SCK

microphone:
  - platform: i2s_audio
    i2s_audio_id: i2s_in
    id: external_microphone
    adc_type: external
    channel: left
    i2s_din_pin: "${i2s_din_pin}"  # SD
    bits_per_sample: 32bit
    sample_rate: 16000

speaker:
  - platform: i2s_audio
    id: va_speaker
    i2s_dout_pin:
      number: ${i2s_speaker_din_pin}
      # allow_other_uses: true
    dac_type: external
    channel: mono

voice_assistant:
  microphone: external_microphone
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  speaker: va_speaker
  use_wake_word: true
  on_listening:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        brightness: 50%
        effect: pulse
  on_tts_start:
    - light.turn_on:
        id: led
        blue: 0%
        red: 0%
        green: 100%
        brightness: 50%
        effect: pulse
  on_end:
    - delay: 100ms
    - script.execute: reset_led
  on_error:
    - light.turn_on:
        id: led
        blue: 0%
        red: 100%
        green: 0%
        brightness: 50%
        effect: none
    - delay: 1s
    - script.execute: reset_led
    - script.wait: reset_led

script:
  - id: reset_led
    then:
      - if:
          condition:
            - switch.is_on: listen_light
          then:
            - light.turn_on:
                id: led
                blue: 100%
                red: 100%
                green: 0%
                brightness: 20%
                effect: none
          else:
            - light.turn_off: led

switch:
  - platform: template
    name: "VA Listen Light"
    id: listen_light
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      - script.execute: reset_led
    on_turn_off:
      - script.execute: reset_led

esphome:
  min_version: 2023.10.0
  on_boot:
    - priority: -100
      then:
        - wait_until: api.connected
        - delay: 1s
        - voice_assistant.start_continuous:

micro_wake_word:
  models:
    - model: alexa
    - model: okay_nabu
  on_wake_word_detected:
    - voice_assistant.start:
        wake_word: !lambda return wake_word;