i2s_audio:
  id: i2s_audiobus
  i2s_lrclk_pin: "${i2s_lrclk_pin}"   # WS
  i2s_bclk_pin: "${i2s_bclk_pin}"     # SCK

microphone:
  - platform: i2s_audio
    id: external_microphone
    channel: left
    adc_type: external
    i2s_din_pin: "${i2s_din_pin}"     # SD
    i2s_audio_id: i2s_audiobus
    pdm: false

speaker:
  - platform: i2s_audiobus
    id: va_speaker
    i2s_dout_pin: ${i2s_dout_pin}
    dac_type: external
    channel: mono

voice_assistant:
  id: va
  microphone: external_microphone
  speaker: va_speaker
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  on_listening:
    - light.turn_on:
        id: led
        effect: strobe
  on_tts_start:
    - light.turn_on:
        id: led
        effect: strobe
  on_end:
    - delay: 100ms
    - script.execute: reset_led
  on_error:
    - light.turn_on:
        id: led
        effect: none
    - delay: 1s
    - script.execute: reset_led
    - script.wait: reset_led

script:
  - id: reset_led
    then:
      - if:
          condition:
            - switch.is_on: listen_light
          then:
            - light.turn_on:
                id: led
                effect: none
          else:
            - light.turn_off: led

switch:
  - platform: template
    name: "VA Listen Light"
    id: listen_light
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      - script.execute: reset_led
    on_turn_off:
      - script.execute: reset_led

esphome:
  min_version: 2023.10.0
  on_boot:
    - priority: -100
      then:
        - wait_until: api.connected
        - delay: 1s
        - voice_assistant.start_continuous: